___

# <font color= #99C8F5> **Predicción de Turistas en México** </font>
#### <font color= #2E9AFE> `Modelos no Lineales para Pronósticos`</font>
<Strong> Isabel Valladolid, Oscar Rocha, Vivienne Toledo </Strong>

_13/05/2026._

___

# <font color= #99C8F5> **Introducción** </font>

alguien aviéntense una intro mamadora

Fuente de datos: https://embamex.sre.gob.mx/filipinas/index.php/visita-mexico/mexico-tourism-data-and-statistics

---

# <font color= #99C8F5> **Librerías y Datos** </font>

In [29]:
# General
import pandas as pd

# Visualizaciones
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "notebook"

In [4]:
df = pd.read_excel('data/BD_Nacionalidad.xlsx')
df.head()

,Año,Fecha,MesNum,Mes,Aeropuerto,Origen,Pais,Región,Sexo,Valor
0,2012,2012/1/1,1,Enero,"Acapulco, Gro.",Nacionalidad,Alemania,Europa,Hombre,1
1,2012,2012/1/1,1,Enero,"Acapulco, Gro.",Nacionalidad,Alemania,Europa,Mujer,1
2,2012,2012/1/1,1,Enero,"Acapulco, Gro.",Nacionalidad,Australia,Oceanía,Hombre,6
3,2012,2012/1/1,1,Enero,"Acapulco, Gro.",Nacionalidad,Australia,Oceanía,Mujer,1
4,2012,2012/1/1,1,Enero,"Acapulco, Gro.",Nacionalidad,Austria,Europa,Hombre,1

In [10]:
# Filter dataset
df = df[['Fecha', 'Valor']]

# Convert date column to datetime
df['Fecha'] = pd.to_datetime(df['Fecha'])

# Group values
df_clean = df.groupby('Fecha')['Valor'].sum().reset_index()
df_clean.head()

       Fecha    Valor
0 2012-01-01  1026996
1 2012-02-01  1042311
2 2012-03-01  1155655
3 2012-04-01   884032
4 2012-05-01   773678

In [ ]:
# Visualizar la serie
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_clean['Fecha'], y=df_clean['Valor'].squeeze(), mode='lines', name='Turistas'))
fig.update_layout(title=f'Turismo en México',
                  yaxis_title='Turistas')
fig.show()